version: '3'
services:
 kong:
    image: kong:latest
    ports:
      - "80:8000"
      - "8443:8443"
    environment:
      KONG_DATABASE: "off"
      KONG_PROXY_ACCESS_LOG: "off"
      KONG_ADMIN_ACCESS_LOG: "off"
      KONG_PROXY_ERROR_LOG: "off"
      KONG_ADMIN_ERROR_LOG: "off"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
